### ISSUE TITLE
Editor - cannot add records on empty database

### ISSUE THREAD

**Issue by ess-acppo-djd** [ess-acppo/nsl-infra#13] opened 2018-07-30 04:33 UTC
Unable to add records to an empty database.
Scientific names cannot be added without a parent using the 'old' dialogue.
The 'new' dialogue for adding names at Family and above will not permit a name to be added at the rank of Family (or above) 
Dialogue throws an "Error: 404"

**Comment by ess-acppo-djd** [comment] 2018-07-30 04:34
![gitissue-nslinfra013](https://user-images.githubusercontent.com/34111282/43377725-a98abe2a-9405-11e8-8eef-dd65729abc74.png)

**Comment by ess-acppo-djd** [comment] 2018-07-30 04:36
While name appears to be written to database (according to logs), it is not 'auto suggested' when trying to use it as a parent.

**Comment by mbohun** [comment] 2018-08-07 09:24
@pmcneil we did re-test this issue today on http://dev55-icn.oztaxa.com/nxl/editor (that is running editor version: https://github.com/bio-org-au/nsl-editor/commit/9675e53469f352fcf4a439b0d8eeacbd91f12285), however the error message is still being shown, even when the actual functionality seems to be fixed (obviously this need a deouble-checking/confirmation).

**Attached:**
- tomcat, webapps' logs
- `$CATALINA_HOME/.nsl` config files
[2018-08-07_BNTi_icn-dev55_logs_conf.zip](https://github.com/ess-acppo/nsl-infra/files/2268533/2018-08-07_BNTi_icn-dev55_logs_conf.zip)

**Comment by pmcneil** [comment] 2018-08-07 23:16
The 404 error is not related at all to the commit you indicate. That was a configuration error on your part to do with authentication of the editor to the mapper IIRCC.

**Comment by pmcneil** [comment] 2018-08-08 01:11
@mbohun note you still have host : 127.0.0.1 in the api.auth : as I mentioned if you have IPV6 enabled on the server this can and will break. For the moment remove the host entry.
2. remove //    jndiName = "java:comp/env/jdbc/apni" line from datasource in services-config.groovy
3. logs are possibly more useful when we know what time the error occurred :-)

**Comment by pmcneil** [comment] 2018-08-08 01:22
OK configuration error in the editor config for the internal links to the services:

Rails.configuration.services = "https://dev55-icn.oztaxa.com/nxl/services/"
Rails.configuration.name_services = "https://dev55-icn.oztaxa.com/nxl/services/name/bpni/"
Rails.configuration.reference_services = "https://dev55-icn.oztaxa.com/nxl/services/reference/bpni/"

They should all be "localhost" and need /rest/ after services/ e.g.

Rails.configuration.services = 'http://localhost:8080/nxl/services/'
Rails.configuration.name_services = 'http://localhost:8080/nxl/services/rest/name/bpni/'
Rails.configuration.reference_services = 'http://localhost:8080/nxl/services/rest/reference/bpni/'

**Comment by mbohun** [comment] 2018-08-08 02:13
adjusted the `$CATALINA_HOME/.nsl` config-s as per @pmcneil advise:
```diff
diff -Naur dot_nsl-2018-08-08_01/editor-config.rb .nsl/editor-config.rb
--- dot_nsl-2018-08-08_01/editor-config.rb	2018-08-08 11:39:25.660257997 +1000
+++ .nsl/editor-config.rb	2018-08-08 11:52:35.159042282 +1000
@@ -3,9 +3,9 @@
 Rails.configuration.nsl_services = "https://dev55-icn.oztaxa.com/nxl/services/"
 Rails.configuration.nsl_links = "https://dev55-icn.oztaxa.com/nxl/services/"
 
-Rails.configuration.services = "https://dev55-icn.oztaxa.com/nxl/services/"
-Rails.configuration.name_services = "https://dev55-icn.oztaxa.com/nxl/services/name/bpni/"
-Rails.configuration.reference_services = "https://dev55-icn.oztaxa.com/nxl/services/reference/bpni/"
+Rails.configuration.services = "http://localhost:8080/nxl/services/"
+Rails.configuration.name_services = "http://localhost:8080/nxl/services/rest/name/bpni/"
+Rails.configuration.reference_services = "http://localhost:8080/nxl/services/rest/reference/bpni/"
 Rails.configuration.api_key = "d0d1e81d-test-apni-editor"
 
 Rails.configuration.ldap_admin_username = "uid=admin,ou=system"
diff -Naur dot_nsl-2018-08-08_01/nsl-mapper-config.groovy .nsl/nsl-mapper-config.groovy
--- dot_nsl-2018-08-08_01/nsl-mapper-config.groovy	2018-08-08 11:39:25.660257997 +1000
+++ .nsl/nsl-mapper-config.groovy	2018-08-08 11:49:10.080554444 +1000
@@ -45,13 +45,11 @@
 api.auth = [
         '558aaeb5-3e5b-4dd3-ad03-d17c2689b70d': [
                 application: 'nxl/services',
-                roles      : ['admin'],
-                host       : '127.0.0.1'
+                roles      : ['admin']
         ],
        'd0d1e81d-test-apni-editor': [
                 application: 'nxl/editor',
-                roles      : ['admin'],
-                host       : '127.0.0.1'
+                roles      : ['admin']
         ]	
 ]
 
diff -Naur dot_nsl-2018-08-08_01/services-config.groovy .nsl/services-config.groovy
--- dot_nsl-2018-08-08_01/services-config.groovy	2018-08-08 11:39:25.660257997 +1000
+++ .nsl/services-config.groovy	2018-08-08 11:43:28.121743863 +1000
@@ -51,7 +51,6 @@
 }
 
 dataSource_nsl {
-//    jndiName = "java:comp/env/jdbc/apni"
                 username = "nsldev"
                 password = "nsldev"
                 url = "jdbc:postgresql://localhost:5432/nsl"
```

and retested the editor, the problem is fixed now.

**Comment by mbohun** [comment] 2018-08-08 02:34
retested the editor, the problem is fixed now.

**Closed as completed** 2018-08-08 02:34 UTC
Labels: bug
